export const MOCK_PROJECTS = [
  {
    id: 1,
    slug: 'clean-water-africa',
    title: 'Clean Water Initiative Africa',
    organization: 'WaterForLife Foundation',
    category: 'Healthcare',
    verified: true,
    featured: true,
    active: true,
    raised: 426798,
    goal: 600000,
    donors: 1842,
    daysLeft: 23,
    tags: ['Water', 'Africa', 'Infrastructure'],
    excerpt: 'Bringing clean, safe drinking water to 50,000 people across rural Kenya and Tanzania.',
    description: `Water scarcity affects millions across sub-Saharan Africa. Our initiative installs 200 borehole wells across 50 villages in Kenya and Tanzania, providing sustainable access to clean water for over 50,000 people.\n\nEach well is equipped with solar-powered pumps, filtration systems, and community maintenance training to ensure long-term sustainability.`,
    banner: 'https://images.unsplash.com/photo-1541844053589-346841d0b34c?w=1200&h=500&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1541844053589-346841d0b34c?w=600',
      'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600',
    ],
    updates: [
      { date: '2024-01-15', title: '25 Wells Completed!', content: 'Excited to announce 25 wells are now operational.' },
      { date: '2024-02-01', title: 'Community Training', content: '200 community members trained in maintenance.' },
    ],
    createdAt: '2023-11-01',
  },
  {
    id: 2,
    slug: 'girls-education-pakistan',
    title: "Girls Education Fund Pakistan",
    organization: 'Bright Futures NGO',
    category: 'Education',
    verified: true,
    featured: true,
    active: true,
    raised: 189500,
    goal: 300000,
    donors: 934,
    daysLeft: 45,
    tags: ['Education', 'Girls', 'Pakistan'],
    excerpt: 'Funding scholarships and school infrastructure for 1,000 girls in rural Pakistan.',
    description: 'Education is the most powerful tool to break cycles of poverty. We fund scholarships, build classrooms, and provide learning materials for girls in underserved communities across Khyber Pakhtunkhwa province.',
    banner: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600'],
    updates: [
      { date: '2024-01-20', title: '500 Scholarships Awarded', content: 'Half our goal reached.' },
    ],
    createdAt: '2023-10-15',
  },
  {
    id: 3,
    slug: 'amazon-reforestation',
    title: 'Amazon Reforestation Project',
    organization: 'Green Planet Alliance',
    category: 'Environment',
    verified: true,
    featured: false,
    active: true,
    raised: 312000,
    goal: 500000,
    donors: 2109,
    daysLeft: 67,
    tags: ['Environment', 'Amazon', 'Climate'],
    excerpt: 'Plant 1 million native trees in deforested areas of the Brazilian Amazon.',
    description: 'The Amazon rainforest is the lungs of our planet. We work with local communities and indigenous groups to replant native species in deforested corridors, restoring biodiversity and carbon sequestration capacity.',
    banner: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600'],
    updates: [],
    createdAt: '2023-09-20',
  },
  {
    id: 4,
    slug: 'food-bank-chicago',
    title: 'Chicago Community Food Bank',
    organization: 'Feed Chicago',
    category: 'Poverty',
    verified: false,
    featured: false,
    active: true,
    raised: 74200,
    goal: 150000,
    donors: 521,
    daysLeft: 30,
    tags: ['Food', 'Chicago', 'Poverty'],
    excerpt: 'Providing nutritious meals to families experiencing food insecurity in Chicago.',
    description: 'Over 1 in 6 Chicagoans face food insecurity. Our network of food banks and mobile pantries delivers fresh produce and prepared meals to families who need it most.',
    banner: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600'],
    updates: [],
    createdAt: '2024-01-05',
  },
  {
    id: 5,
    slug: 'solar-schools-india',
    title: 'Solar Schools India',
    organization: 'SunLight Education',
    category: 'Technology',
    verified: true,
    featured: true,
    active: true,
    raised: 98000,
    goal: 200000,
    donors: 678,
    daysLeft: 55,
    tags: ['Solar', 'Education', 'India'],
    excerpt: 'Installing solar panels in 100 off-grid schools across rural India.',
    description: 'Thousands of rural Indian schools lack reliable electricity. We install solar microgrids that power classrooms, computer labs, and provide clean cooking energy for school kitchens.',
    banner: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600'],
    updates: [],
    createdAt: '2024-01-10',
  },
  {
    id: 6,
    slug: 'ocean-plastic-cleanup',
    title: 'Pacific Ocean Plastic Cleanup',
    organization: 'OceanGuard',
    category: 'Environment',
    verified: true,
    featured: false,
    active: true,
    raised: 541000,
    goal: 750000,
    donors: 3421,
    daysLeft: 12,
    tags: ['Ocean', 'Plastic', 'Marine'],
    excerpt: 'Deploying advanced systems to remove 100 tons of plastic from the Pacific.',
    description: 'The Great Pacific Garbage Patch contains an estimated 80,000 metric tons of plastic. Our autonomous collection systems and clean-up vessels work continuously to extract microplastics and larger debris.',
    banner: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600'],
    updates: [
      { date: '2024-02-10', title: '50 Tons Removed!', content: 'Halfway to our annual cleanup goal.' },
    ],
    createdAt: '2023-08-01',
  },
];

export const MOCK_POSTS = [
  {
    id: 1,
    slug: 'introducing-1st-causes-qf-round',
    title: 'Introducing the 1st Causes QF Round',
    excerpt: 'A new Quadratic Funding QF round is here, taking on Causes! Projects will be funded by the community through our matching pool.',
    content: 'Full blog post content here...',
    image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=600&h=340&fit=crop',
    category: 'Announcement',
    featured: true,
    createdAt: '2024-02-01',
  },
  {
    id: 2,
    slug: 'how-quadratic-funding-works',
    title: 'How Quadratic Funding Works',
    excerpt: 'Quadratic Funding amplifies small donations and democratizes access to resources for public goods.',
    content: 'Full blog post content...',
    image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=600&h=340&fit=crop',
    category: 'Education',
    featured: false,
    createdAt: '2024-01-20',
  },
  {
    id: 3,
    slug: 'impact-report-2023',
    title: 'Impact Report 2023: Year in Review',
    excerpt: 'We helped raise over $5 million for 200+ projects in 2023. Here\'s a look at the incredible impact made by our community.',
    content: 'Full blog post content...',
    image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=600&h=340&fit=crop',
    category: 'Impact',
    featured: false,
    createdAt: '2024-01-05',
  },
  {
    id: 4,
    slug: 'crypto-donations-guide',
    title: 'Your Guide to Crypto Donations',
    excerpt: 'Donating with cryptocurrency is easier than ever. Everything you need to know to make your first crypto donation.',
    content: 'Full blog post content...',
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=600&h=340&fit=crop',
    category: 'Guide',
    featured: false,
    createdAt: '2023-12-15',
  },
];

export const MOCK_PARTNERS = [
  { id: 1, name: 'Dappnode', logo: '🌐' },
  { id: 2, name: 'Gnosis', logo: '🦉' },
  { id: 3, name: 'CoStack', logo: '🌿' },
  { id: 4, name: 'Gitcoin', logo: '🔮' },
  { id: 5, name: 'ShapDAO', logo: '🦊' },
];

export const MOCK_STATS = [
  { label: 'Projects on Platform', value: '7,590', icon: '📋' },
  { label: 'Donated to Projects', value: '~$5,394,840', icon: '💰' },
  { label: '# of Givers', value: '25,713', icon: '🤝' },
];

export const MOCK_FAQS = [
  {
    id: 1, category: 'General',
    question: 'What is HopeFund?',
    answer: 'HopeFund is a charity donation platform that connects donors with verified non-profit projects worldwide. We use innovative mechanisms like Quadratic Funding to amplify the impact of every donation.',
  },
  {
    id: 2, category: 'General',
    question: 'How do I know my donation reaches the right place?',
    answer: 'All projects undergo a rigorous verification process. We verify the identity and credentials of project organizers, track fund disbursements on-chain, and publish regular impact reports.',
  },
  {
    id: 3, category: 'Donations',
    question: 'What payment methods are accepted?',
    answer: 'We accept major cryptocurrencies (ETH, BTC, USDC, DAI), credit/debit cards, and bank transfers. Crypto donations may be tax-deductible depending on your jurisdiction.',
  },
  {
    id: 4, category: 'Donations',
    question: 'Is there a minimum donation amount?',
    answer: 'There is no minimum donation amount. Every contribution, no matter how small, makes a difference and counts toward the Quadratic Funding matching calculation.',
  },
  {
    id: 5, category: 'Projects',
    question: 'How can I submit a project?',
    answer: "Click the \"+ Create\" button in the navigation bar and follow the project creation wizard. You'll need to provide project details, proof of identity, and agree to our terms of service.",
  },
  {
    id: 6, category: 'Projects',
    question: 'How long does project verification take?',
    answer: 'Our team reviews new project applications within 3-5 business days. We may reach out for additional documentation during the review process.',
  },
  {
    id: 7, category: 'Community',
    question: 'How does Quadratic Funding work?',
    answer: 'Quadratic Funding matches donations based on the number of unique donors rather than just the amount. A project with 100 donors of $1 each receives more matching than 1 donor of $100.',
  },
  {
    id: 8, category: 'Community',
    question: 'Can I become a platform partner?',
    answer: 'Absolutely! We welcome partnerships with companies, DAOs, and organizations that share our mission. Reach out to us at partnerships@hopefund.io.',
  },
];

export const MOCK_UPDATES = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=120&h=80&fit=crop',
    title: 'QF Round 3 Kicks Off',
    date: '2h ago',
  },
  {
    id: 2,
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=120&h=80&fit=crop',
    title: 'New Partner: Gnosis Chain',
    date: '5h ago',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=120&h=80&fit=crop',
    title: '$1M Milestone Reached',
    date: '1d ago',
  },
];